name: Bug Report
description: Report a reproducible bug
title: "[bug] "
labels: ["bug"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened?
      placeholder: Clear and concise description of the issue.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps To Reproduce
      description: List exact steps.
      placeholder: |
        1. Go to ...
        2. Click ...
        3. See error ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / Screenshots
      description: Paste relevant errors, stack traces, or screenshots.

  - type: input
    id: node
    attributes:
      label: Node Version
      placeholder: e.g. v20.18.0

  - type: input
    id: browser
    attributes:
      label: Browser
      placeholder: e.g. Chrome 131

  - type: input
    id: os
    attributes:
      label: OS
      placeholder: e.g. macOS 15.2
