name: Feature Request
description: Propose a new feature or enhancement
title: "[feature] "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem are you trying to solve?
      placeholder: Describe the user need or migration pain point.
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed Solution
      placeholder: Describe your proposed approach.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      placeholder: Any alternatives you evaluated?

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      placeholder: Links, screenshots, or references.
